/**
 * Generating
 * 
 * [Environments]
 * SHIINA_ENV*
 * > SHIINA_INSTANCE*
 * > SHIINA_TOKEN*
 * 
 * SHIINA_DBPATH: DB保存先
 */



const Mastodon = require("mastodon-api");

const Initializer = require("./../../libs/Initializer");
const Logger = require("./../../libs/Logger");
const Generator = require("./../../libs/Generator");



/** @type {Initializer.ShiinaEnv} */
const ENV = process.env;

const mstdn = new Mastodon({ api_url: `${ENV.SHIINA_INSTANCE}/api/v1/`, access_token: ENV.SHIINA_TOKEN });
const generator = new Generator();

const dialogue = new Logger.AsyncArrayLogger(`${ENV.SHIINA_HOMEDIR}/${ENV.SHIINA_DBPATH}`);
dialogue.on("initialized").then(dialogue => {
	generator.importDatabase(dialogue.log);

	//Generating sentences
	const tootingQues = [];
	for (let i = 0; i < 10; i++) {
		const status = generator.generate();

		console.info("== Generated by Shiina ==");
		console.log(status);

		if (!ENV.DOES_TOOT) continue;

		tootingQues.push(
			mstdn.post("statuses", {
				status,
				spoiler_text: "== Generated by Shiina ==",
				
				visibility: "unlisted"
			})
		);
	}

	return Promise.all(tootingQues);
}).then(() => process.kill(process.pid));